{% set name = "csdms-topoflow-meteorology" %}
{% set version = "3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/topoflow-bridge

requirements:
  build:
    - bmi-babel
    - topoflow
  run:
    - bmi-babel
    - topoflow

test:
  requires:
    - pymt
    - bmi-tester

about:
  home: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Meteorology
  license: Apache
  summary: |
    The Meteorology component, a part of the spatially
    distributed hydrologic model TopoFlow, reads a variety of variables
    for the atmosphere and for the land surface from input files or as
    simple scalars. It then computes many additional variables, such as
    vapor pressure and net shortwave (solar) radiation, using built-in
    shortwave and longwave radiation calculators that are based on
    celestial mechanics and widely-used empirical relationships. These
    additional variables are needed by the SnowEnergyBalance and
    EvapEnergyBalance components. Direct, diffuse and back-scattered
    radiation fluxes are all modeled. Properties of the atmosphere
    (e.g. precipitation rate, air temperature, relative humidity, and
    dust attenuation), are used, as well as surface/topographic
    properties (e.g. slope angle, aspect angle and surface albedo). The
    approach used here closely follows the one outlined in Appendix E of
    Dingman (2002). However, instantaneous vs. day-integrated radiation
    fluxes are used and the optical air mass is modeled using the widely
    used method of Kasten and Young (1989).
